# Generated by Django 2.0.5 on 2018-12-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
